export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST"
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL"

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL"

export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST"
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS"
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL"

export const GET_INVOICES_REQUEST = "GET_INVOICES_REQUEST"
export const GET_INVOICES_SUCCESS = "GET_INVOICES_SUCCESS"
export const GET_INVOICES_FAIL = "GET_INVOICES_FAIL"

export const SEARCH_INVOICES_REQUEST = "SEARCH_INVOICES_REQUEST"
export const SEARCH_INVOICES_SUCCESS = "SEARCH_INVOICES_SUCCESS"
export const SEARCH_INVOICES_FAIL = "SEARCH_INVOICES_FAIL"

export const SET_INVOICE_BACK = "SET_INVOICE_BACK"

export const GET_ALL_INVOICES = "GET_ALL_INVOICES"

export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE"

export const SAVE_CLIENT_REQUEST ="SAVE_CLIENT_REQUEST"
export const SAVE_CLIENT_SUCCESS ="SAVE_CLIENT_SUCCESS"
export const SAVE_CLIENT_FAIL ="SAVE_CLIENT_FAIL"

export const GET_CLIENT_INVOICES_REQUEST = "GET_CLIENT_INVOICES_REQUEST"
export const GET_CLIENT_INVOICES_SUCCESS = "GET_CLIENT_INVOICES_SUCCESS"
export const GET_CLIENT_INVOICES_FAIL = "GET_CLIENT_INVOICES_FAIL"

export const SET_PAID_REQUEST = "SET_PAID_REQUEST"
export const SET_PAID_SUCCESS = "SET_PAID_SUCCESS"
export const SET_PAID_FAIL = "SET_PAID_FAIL"

export const CREATE_INVOICE_REQUEST = "CREATE_INVOICE_REQUEST"
export const CREATE_INVOICE_SUCCESS = "CREATE_INVOICE_SUCCESS"
export const CREATE_INVOICE_FAIL = "CREATE_INVOICE_FAIL"

export const SET_TOTAL_AMOUNT_REQUEST = "SET_TOTAL_AMOUNT_REQUEST"
export const SET_TOTAL_AMOUNT_SUCCESS = "SET_TOTAL_AMOUNT_SUCCESS"
export const SET_TOTAL_AMOUNT_FAIL = "SET_TOTAL_AMOUNT_FAIL"

export const DELETE_INVOICE_REQUEST = "DELETE_INVOICE_REQUEST"
export const DELETE_INVOICE_SUCCESS = "DELETE_INVOICE_SUCCESS"
export const DELETE_INVOICE_FAIL = "DELETE_INVOICE_FAIL"

export const SET_TOTAL_AMOUNT_MINUS_REQUEST = "SET_TOTAL_AMOUNT_MINUS_REQUEST"
export const SET_TOTAL_AMOUNT_MINUS_SUCCESS = "SET_TOTAL_AMOUNT_MINUS_SUCCESS"
export const SET_TOTAL_AMOUNT_MINUS_FAIL = "SET_TOTAL_AMOUNT_MINUS_FAIL"

export const SEARCH_CLIENT_REQUEST = "SEARCH_CLIENT_REQUEST"
export const SEARCH_CLIENT_SUCCESS = "SEARCH_CLIENT_SUCCESS"
export const SEARCH_CLIENT_FAIL = "SEARCH_CLIENT_FAIL"

export const GET_ALL_CLIENTS = "GET_ALL_CLIENTS"
export const SET_PAID_ERROR = "SET_PAID_ERROR"

export const SET_CURRENT_CLIENT = "SET_CURRENT_CLIENT"

export const SEARCH_CLIENTINVOICES_REQUEST= "SEARCH_CLIENTINVOICES_REQUEST"
export const SEARCH_CLIENTINVOICES_SUCCESS = "SEARCH_CLIENTINVOICES_SUCCESS"
export const SEARCH_CLIENTINVOICES_FAIL = "SEARCH_CLIENTINVOICES_FAIL"